version: '3'

services:
  web:
    restart: always
    build: ./django
    ports:
      - 8060:8000
        #environment:
      #DEBUG: 'true'
      #command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
  nginx:
    build: ./nginx
    ports:
      - 8080:80

